### ISSUE TITLE
Call to undefined function Sodium\randombytes_buf()

### ISSUE THREAD

**Issue by bluebaroncanada** [paragonie/halite#55]
Getting this error with circlical and zf3 on a vagrant machine ubuntu 16.04

```
vagrant@vagrant:/usr/lib/php/20151012$ pecl search libsodium
Retrieving data...0%
Matched packages, channel pecl.php.net:
=======================================
Package   Stable/(Latest) Local
libsodium 1.0.6 (stable)  1.0.6 Wrapper for the Sodium cryptographic library
vagrant@vagrant:/usr/lib/php/20151012$ apt-cache policy libsodium-dev
libsodium-dev:
  Installed: 1.0.8-5
  Candidate: 1.0.8-5
  Version table:
 *** 1.0.8-5 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
```

/var/www/vendor/paragonie/halite/src/KeyFactory.php:51

# Call to undefined function Sodium\randombytes_buf()

#0 /var/www/vendor/saeven/zf3-circlical-user/src/CirclicalUser/Service/AuthenticationService.php(542): ParagonIE\Halite\KeyFactory::generateEncryptionKey()
#1 /var/www/module/Application/src/Service/AdminService.php(60): CirclicalUser\Service\AuthenticationService->registerAuthenticationRecord(Object(Application\Entity\User), 'bluebaroncanada...', 'test')
#2 /var/www/module/Application/src/Controller/AdminController.php(46): Application\Service\AdminService->createUser('bluebaroncanada...', 'test', true)
#3 /var/www/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Application\Controller\AdminController->createUserAction()
#4 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#7 /var/www/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#11 /var/www/public/index.php(49): Zend\Mvc\Application->run()
#12 {main}

**Comment by bluebaroncanada** [comment]
Turns out I didn't have libsodium in my php.ini conf.  i had put it in my cli conf but not in the apache conf.
